tmux
neovim
wl-clipboard
kitty
starship
zoxide
fzf
trash-cli
pika-backup
keepass
sws
reflector
lazygit
unzip
rapid-photo-downloader
fd
less
man-db
bat
amd-ucode
blueman
btop
dunst
fd
fwupd
git
hyprpaper
hyprpolkitagent
musescore
ntfs-3g
obsidian
openssh
pipewire
reaper
reapack
restic
rofi
tree-sitter-cli
vim 
vulkan-radeon
waybar
whosthere-bin
yay
